### ISSUE TITLE
Documentation on "Team Members" page

### ISSUE THREAD

**Issue by niranjanthiru** [morethanthemes/showcase-lite#4]
Please share the steps to reproduce the Team Members page design.

**Comment by vkechagias** [comment]
Hi there,

the Team Members page you see on the demo is a basic page with simple HTML markup.

You can install a temp instance of the demo content based on this repo and simply edit the page and copy over the markup to your installation.

You can expose the HTML markup by clicking the source button in CKEditor. Finally make sure that you are using the Full HTML text format on your page.

https://www.screencast.com/t/cPnx4LrBPo

Cheers,
Bill

**Comment by niranjanthiru** [comment]
Thanks for the response, Bill. The screenshot helped me
